# URL para MySQL (puerto 3306)
spring.datasource.url=jdbc:mysql://localhost:3306/proyectoFinalCamiones?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=romano3442

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true