# URL para MySQL (puerto 3306)
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_de_camiones?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true