# URL para MySQL (puerto 3306)
spring.datasource.url=jdbc:mysql://localhost:3306/proyectoFinalCamiones?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Romano3442

# Dialecto para que Hibernate sepa que vamos a usar funciones de mapas en MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true